travis:
  secure:
    BINSTAR_TOKEN: pkDwyiONWUEDHAGU6aLqCQyNaz7Tiu7rgHUNRbCC8rlheoMN6PRXdAfWsB2ZzSpxtfvFz5mxOa4627Dkfa11msPLb9JrXt7acL01HORYK6FVCboJ9Ijswr/eLJOZbyoRY2AAWaxCnBnM0KI4DrJFpIFOSEy6hvBy5fyo55Y8gAuBrZ/0ywI9McFZcnTbO5Ev4oeAVjXQVP9RojnyrTGGglP4/uCgWOCGEkWiS7VLjze6HYMyleeh35Gh2HGO+4D1yxcqOujbQGoRys0veGnsmQiJnWIFhDQsMdXYHwMzMwb4tsAE2en/DxhbdSUTsUo/kBEOW26zZTzZOQxEOVAOad+S040msjlWnqWjEnAhIrgjnmyBRNZyl6VZAGkY2Ygo2+nyOQS4zNiu+9ggxwdFLxnSlEF9EkvrCqx25khkopVrt9FNBzlfr2ZB0ClSUaWO3sHMrzdYountF4jSOLs1oewtNhIG2QvQeujFsSaauksuXJVFM8fa1m/o6rbBeRxv7EAr0RYAy/p3h1tluNEaTovBam8moXJmnzgr8smboQRjfMEE6k0Jm19Hv8HvEJfj3lXAI1ZCUqZJ4PfsgtUpzoS4iQK18CDgq0dZqUxICmx/wYe/HQ/GVXuqf6TMk1M9MgcMLcZ7OB68wH0MTlvpVJoYkIG0PErfeKuWxJyQfN4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
